// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _05_Fiap.Web.AspNet.Persistence;

namespace _05_Fiap.Web.AspNet.Migrations
{
    [DbContext(typeof(AllZooContext))]
    [Migration("20190905163208_inicioanimal")]
    partial class inicioanimal
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_05_Fiap.Web.AspNet.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Carnivoro");

                    b.Property<string>("Nome")
                        .HasMaxLength(50);

                    b.Property<int>("Tipo");

                    b.HasKey("AnimalId");

                    b.ToTable("TB_ANIMAAL");
                });

            modelBuilder.Entity("_05_Fiap.Web.AspNet.Models.Zoo", b =>
                {
                    b.Property<int>("ZooId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnName("Data Abertura");

                    b.Property<int>("EntidadeAdministradora")
                        .HasColumnName("Entidade administradora");

                    b.Property<int>("Jaulas")
                        .HasColumnName("Jaula");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("Nome")
                        .HasMaxLength(50);

                    b.HasKey("ZooId");

                    b.ToTable("TB_ZOO");
                });
#pragma warning restore 612, 618
        }
    }
}
